# Generated by Django 2.1.1 on 2019-03-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='maps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=128, unique=True, verbose_name='Username')),
                ('Password', models.CharField(max_length=128, verbose_name='Password')),
            ],
        ),
    ]
