# Generated by Django 2.1.1 on 2019-03-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='Username',
            field=models.CharField(max_length=128, verbose_name='Username'),
        ),
    ]
